# Generated by Django 4.1.5 on 2023-01-10 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_alter_advertisement_id_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='in_favorite_users',
            field=models.ManyToManyField(related_name='favorite_advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
