# Generated by Django 4.1.4 on 2022-12-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Связанный объект', 'verbose_name_plural': 'Связанные объекты'},
        ),
    ]
