# Generated by Django 4.1.4 on 2022-12-19 19:12

from django.db import migrations, models
import measurement.utils


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to=measurement.utils.upload_directory_path, verbose_name='Снимок'),
        ),
    ]
