# Generated by Django 4.1.3 on 2022-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
